#Set of H2 datatypes to java.sql.Types
#https://www.h2database.com/html/datatypes.html

CHARACTER=VARCHAR
CHAR=VARCHAR
NCHAR=VARCHAR

CHARACTER\u0020VARYING=VARCHAR
VARCHAR=VARCHAR
NATIONAL\u0020CHARACTER\u0020VARYING=VARCHAR
NATIONAL\u0020CHAR\u0020VARYING=VARCHAR
VARCHAR_CASESENSITIVE=VARCHAR

CHARACTER\u0020LARGE\u0020OBJECT=CLOB
CHAR\u0020LARGE\u0020OBJECT=CLOB
CLOB=CLOB
NATIONAL\u0020CHARACTER\u0020LARGE\u0020OBJECT=CLOB
NCHAR\u0020LARGE\u0020OBJECT=CLOB
NCLOB=CLOB

VARCHAR_IGNORECASE=VARCHAR

BINARY=BINARY

BINARY\u0020VARYING=VARBINARY
VARBINARY=VARBINARY

BINARY\u0020LARGE\u0020OBJECT=BLOB
BLOB=BLOB

BOOLEAN=BIT

TINYINT=TINYINT

SMALLINT=SMALLINT

INTEGER=INTEGER
INT=INTEGER

BIGINT=BIGINT

NUMERIC=NUMERIC
DECIMAL=DECIMAL
DEC=DECIMAL

REAL=REAL
FLOAT=FLOAT

DOUBLE\u0020PRECISION=DOUBLE

DECFLOAT=DECIMAL

DATE=DATE
TIME=TIME
TIME\u0020WITH\u0020TIMEZONE=TIMESTAMP
TIMESTAMP=TIMESTAMP
TIMESTAMP\u0020WITH\u0020TIMEZONE=TIMESTAMP
#INTERVAL=
JAVA_OBJECT=JAVA_OBJECT

ENUM=VARCHAR

GEOMETRY=VARCHAR

JSON=BINARY

UUID=BINARY

ARRAY=JAVA_OBJECT

#ROW=

INTERVAL\u0020YEAR=
INTERVAL\u0020MONTH=
INTERVAL\u0020DAY=
INTERVAL\u0020HOUR=
INTERVAL\u0020MINUTE=
INTERVAL\u0020SECOND=
INTERVAL\u0020YEAR\u0020TO\u0020MONTH=
INTERVAL\u0020DAY\u0020TO\u0020HOUR=
INTERVAL\u0020DAY\u0020TO\u0020MINUTE=
INTERVAL\u0020DAY\u0020TO\u0020SECOND=
INTERVAL\u0020HOUR\u0020TO\u0020MINUTE=
INTERVAL\u0020HOUR\u0020TO\u0020SECOND=
INTERVAL\u0020MINUTE\u0020TO\u0020SECOND=
