#Set of Oracle datatypes to java.sql.Types
#https://docs.oracle.com/cd/A97335_02/apps.102/a83724/basic3.htm

#+ "decode(a.data_type, 'FLOAT',decode(a.data_precision,null, "
#+ "a.data_length, a.data_precision), 'NUMBER', decode(a.data_precision,null, "
#+ "a.data_length, a.data_precision), a.data_length) as COLUMN_SIZE, "

# ORACLE TYPE, java.sql.Types value
# 'CHAR',1,
# 'DATE',91,
# 'FLOAT',6,
# 'LONG',-1,
# 'NUMBER',2,
# 'VARCHAR2',12,
# 'BFILE',-13, "
# 'BLOB',2004,
# 'CLOB',2005,
# 'MLSLABEL',1111,
# 'NCHAR',1,
# 'NCLOB',2005,
# 'NVARCHAR2',12, "
# 'RAW',-3,
# 'ROWID',1111,
# 'UROWID',1111,
# 'LONG RAW', -4, "
# 'TIMESTAMP', 93,
# 'XMLTYPE',2005,
# anything else 1111

VARCHAR2=VARCHAR
NVARCHAR2=VARCHAR
NUMBER=NUMERIC
FLOAT=FLOAT
LONG=LONGVARCHAR
DATE=TIMESTAMP
BINARY_FLOAT=REAL
BINARY_DOUBLE=DOUBLE
TIMESTAMP=TIMESTAMP
#TIMESTAMP WITH TIME ZONE=
#TIMESTAMP WITH LOCAL TIME ZONE=
#INTERVAL YEAR TO TO MONTH=
#INTERVAL DAY TO SECOND=
RAW=VARBINARY
LONG\u0020RAW=LONGVARBINARY
ROWID=OTHER
UROWID=OTHER
CHAR=CHAR
NCHAR=CHAR
CLOB=CLOB
NCLOB=CLOB
BLOB=BLOB
#BFILE=
