#Set of Sqlite datatypes to java.sql.Types
#https://www.sqlite.org/datatype3.html

INTEGER=INTEGER
INT=INTEGER
TINYINT=TINYINT
SMALLINT=SMALLINT
MEDIUMINT=INTEGER
BIGINT=INTEGER
#UNSIGNED\u0020BIG\u0020INT=
INT2=INTEGER
INT8=INTEGER

TEXT=VARCHAR
CHARACTER=VARCHAR
VARCHAR=VARCHAR
VARYING\u0020CHARACTER=VARCHAR
NCHAR=VARCHAR
NATIVE CHARACTER=VARCHAR
NVARCHAR=VARCHAR
CLOB=CLOB

BLOB=BLOB

REAL=REAL
DOUBLE=DOUBLE
DOUBLE\u0020PRECISION=DOUBLE
FLOAT=FLOAT

NUMERIC=NUMERIC
DECIMAL=DECIMAL
BOOLEAN=BIT
DATE=DATE
DATETIME=TIMESTAMP
