package ${basePackagePath}.model;

/**
 * <p>Entity for ${table.javaName}.</p>
 * <p><b>NOTE:</b>if this class is re-generated any changes will be lost, extend this interface if you wish to
 * add functionality</p>
 *
 * @author ${author}
 * @version ${version}
 * @see ${basePackagePath}.model.${table.javaName}
 */
@Generated(
    value = "${author}",
    date = "${buildDtm}",
    comments = "This code was generated by tools for use with Java applications using Hibernate and Spring Data."
)
@Entity
@Table(name = "${table.name}")
public class ${table.javaName} {

    //TODO: properties with annotations

    //TODO: collections

    /** Default constructor. */
    ${tableEntity.getConstructorNoArgs()}

    //TODO: minimum args constructor
    ${tableEntity.getConstructorRequiredArgs()}

    //TODO: all args constructor
    ${tableEntity.getConstructorAllArgs()}

    //TODO: getters/setters

    //TODO: toString

    //TODO: hashCode

}